# library_loader.py


def get_default_machinery():
  """Returns baseline machinery library with 12 comprehensive industrial equipment specifications."""
  return [
      {
          "Make": "Mazak",
          "Model": "Integrex i-200",
          "Type": "Multi axis CNC",
          "Width": 12.0,
          "Height": 10.0,
          "Standoff": 5.0,
          "VaporPort": "VP-A1",
          "WaterHookup": True,
          "Amperage": 45.0,
          "Wattage": 18000.0,
          "ToolHeads": 4,
          "Volume": 45,
          "Yield": 98.0,
          "CraneRequired": True,
          "Decibel": 75,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Arburg",
          "Model": "Allrounder 370",
          "Type": "Injection Molding",
          "Width": 15.0,
          "Height": 8.0,
          "Standoff": 4.0,
          "VaporPort": "VP-B2",
          "WaterHookup": True,
          "Amperage": 30.0,
          "Wattage": 15000.0,
          "ToolHeads": 1,
          "Volume": 60,
          "Yield": 95.0,
          "CraneRequired": False,
          "Decibel": 65,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Timesavers",
          "Model": "Model 2200",
          "Type": "Sanding/Grinding",
          "Width": 10.0,
          "Height": 7.0,
          "Standoff": 6.0,
          "VaporPort": "VP-C3",
          "WaterHookup": False,
          "Amperage": 25.0,
          "Wattage": 12000.0,
          "ToolHeads": 2,
          "Volume": 35,
          "Yield": 92.0,
          "CraneRequired": False,
          "Decibel": 85,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Haas",
          "Model": "VF-4 Vertical Machining Center",
          "Type": "Multi axis CNC",
          "Width": 11.5,
          "Height": 9.0,
          "Standoff": 4.5,
          "VaporPort": "VP-A2",
          "WaterHookup": True,
          "Amperage": 40.0,
          "Wattage": 16000.0,
          "ToolHeads": 1,
          "Volume": 50,
          "Yield": 97.5,
          "CraneRequired": True,
          "Decibel": 78,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "TRUMPF",
          "Model": "TruLaser 3030 Fiber",
          "Type": "Laser/Plasma Cutter",
          "Width": 18.0,
          "Height": 12.0,
          "Standoff": 6.0,
          "VaporPort": "VP-EX1",
          "WaterHookup": True,
          "Amperage": 60.0,
          "Wattage": 24000.0,
          "ToolHeads": 1,
          "Volume": 80,
          "Yield": 99.0,
          "CraneRequired": True,
          "Decibel": 82,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Amada",
          "Model": "HG 1003 Press Brake",
          "Type": "Material Press",
          "Width": 14.0,
          "Height": 8.5,
          "Standoff": 5.0,
          "VaporPort": "VP-NONE",
          "WaterHookup": False,
          "Amperage": 35.0,
          "Wattage": 14000.0,
          "ToolHeads": 1,
          "Volume": 40,
          "Yield": 96.0,
          "CraneRequired": True,
          "Decibel": 72,
          "HumanInterventionRequired": True,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "FANUC",
          "Model": "M-20iD/25 Industrial Robot",
          "Type": "Robotic Assembly",
          "Width": 6.0,
          "Height": 6.0,
          "Standoff": 5.0,
          "VaporPort": "VP-NONE",
          "WaterHookup": False,
          "Amperage": 15.0,
          "Wattage": 6000.0,
          "ToolHeads": 1,
          "Volume": 120,
          "Yield": 99.5,
          "CraneRequired": False,
          "Decibel": 58,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Doosan",
          "Model": "PUMA 2600SY II Lathe",
          "Type": "Lathe",
          "Width": 13.0,
          "Height": 7.5,
          "Standoff": 4.0,
          "VaporPort": "VP-A3",
          "WaterHookup": True,
          "Amperage": 38.0,
          "Wattage": 15500.0,
          "ToolHeads": 2,
          "Volume": 55,
          "Yield": 97.0,
          "CraneRequired": True,
          "Decibel": 76,
          "HumanInterventionRequired": True,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Schuler",
          "Model": "Servo Stamping Press 400T",
          "Type": "Forging",
          "Width": 22.0,
          "Height": 16.0,
          "Standoff": 8.0,
          "VaporPort": "VP-EX2",
          "WaterHookup": True,
          "Amperage": 110.0,
          "Wattage": 45000.0,
          "ToolHeads": 1,
          "Volume": 90,
          "Yield": 94.5,
          "CraneRequired": True,
          "Decibel": 92,
          "HumanInterventionRequired": True,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Kuka",
          "Model": "KR QUANTEC Palletizing Robot",
          "Type": "Packaging",
          "Width": 8.0,
          "Height": 8.0,
          "Standoff": 5.5,
          "VaporPort": "VP-NONE",
          "WaterHookup": False,
          "Amperage": 20.0,
          "Wattage": 8000.0,
          "ToolHeads": 1,
          "Volume": 110,
          "Yield": 99.2,
          "CraneRequired": False,
          "Decibel": 62,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Cheto",
          "Model": "IXN 200 Deep Hole Drilling Machine",
          "Type": "Drilling",
          "Width": 16.0,
          "Height": 11.0,
          "Standoff": 5.0,
          "VaporPort": "VP-D1",
          "WaterHookup": True,
          "Amperage": 50.0,
          "Wattage": 20000.0,
          "ToolHeads": 3,
          "Volume": 30,
          "Yield": 96.8,
          "CraneRequired": True,
          "Decibel": 80,
          "HumanInterventionRequired": True,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
      {
          "Make": "Bystronic",
          "Model": "BySmart Fiber 4020",
          "Type": "Laser/Plasma Cutter",
          "Width": 20.0,
          "Height": 13.0,
          "Standoff": 6.5,
          "VaporPort": "VP-EX3",
          "WaterHookup": True,
          "Amperage": 75.0,
          "Wattage": 30000.0,
          "ToolHeads": 1,
          "Volume": 85,
          "Yield": 98.8,
          "CraneRequired": True,
          "Decibel": 84,
          "HumanInterventionRequired": False,
          "PreferredUtilityZone": "",
          "ProcessFamily": "",
          "ValueAddedPrimary": True,
      },
  ]


def get_default_lighting():
  """Returns standard lighting fixtures library with 10 commercial industrial fixtures."""
  return [
      {
          "Make": "Lithonia",
          "Brand": "I-Beam High Bay",
          "Type": "LED",
          "Wattage": 150.0,
          "Kelvin": 5000,
          "Dimmable": True,
          "Lumens": 18000,
          "Lux": 500,
      },
      {
          "Make": "Philips",
          "Brand": "Halogen Pro",
          "Type": "Halogen",
          "Wattage": 250.0,
          "Kelvin": 3000,
          "Dimmable": True,
          "Lumens": 12000,
          "Lux": 350,
      },
      {
          "Make": "Cree Lighting",
          "Brand": "CXB High Bay Series",
          "Type": "LED",
          "Wattage": 240.0,
          "Kelvin": 4000,
          "Dimmable": True,
          "Lumens": 24000,
          "Lux": 650,
      },
      {
          "Make": "Eaton-Cooper",
          "Brand": "LUMA-FIT High Bay",
          "Type": "LED",
          "Wattage": 180.0,
          "Kelvin": 5000,
          "Dimmable": True,
          "Lumens": 21000,
          "Lux": 580,
      },
      {
          "Make": "Hubbell",
          "Brand": "Industrial High Bay HBL",
          "Type": "LED",
          "Wattage": 210.0,
          "Kelvin": 4000,
          "Dimmable": False,
          "Lumens": 26000,
          "Lux": 700,
      },
      {
          "Make": "Acuity Brands",
          "Brand": "JBL Industrial Strip",
          "Type": "LED",
          "Wattage": 90.0,
          "Kelvin": 3500,
          "Dimmable": True,
          "Lumens": 11000,
          "Lux": 300,
      },
      {
          "Make": "Sylvania",
          "Brand": "Metal Halide Super",
          "Type": "Incandescent",
          "Wattage": 400.0,
          "Kelvin": 4200,
          "Dimmable": False,
          "Lumens": 15000,
          "Lux": 400,
      },
      {
          "Make": "GE Current",
          "Brand": "Albeo ABV3 High Bay",
          "Type": "LED",
          "Wattage": 160.0,
          "Kelvin": 5000,
          "Dimmable": True,
          "Lumens": 20000,
          "Lux": 550,
      },
      {
          "Make": "Dialight",
          "Brand": "Vigilant High Bay",
          "Type": "LED",
          "Wattage": 130.0,
          "Kelvin": 5000,
          "Dimmable": True,
          "Lumens": 18000,
          "Lux": 480,
      },
      {
          "Make": "Rab Lighting",
          "Brand": "BayLED 104W",
          "Type": "LED",
          "Wattage": 104.0,
          "Kelvin": 4000,
          "Dimmable": True,
          "Lumens": 13500,
          "Lux": 380,
      },
  ]


def get_default_cranes():
  """Returns baseline overhead crane library with 10 heavy industrial cranes."""
  return [
      {
          "Make": "Konecranes",
          "Model": "CXT 10T Overhead Crane",
          "MaxLiftWeight": 10.0,
          "MaxLiftSpeed": 25.0,
          "MaxTransversalSpeed": 120.0,
      },
      {
          "Make": "Demag",
          "Model": "EKKE 5T Single Girder",
          "MaxLiftWeight": 5.0,
          "MaxLiftSpeed": 32.0,
          "MaxTransversalSpeed": 160.0,
      },
      {
          "Make": "Gorbel",
          "Model": "Free Standing Bridge Crane 2T",
          "MaxLiftWeight": 2.0,
          "MaxLiftSpeed": 40.0,
          "MaxTransversalSpeed": 200.0,
      },
      {
          "Make": "Harrington",
          "Model": "ED Dual Speed 15T",
          "MaxLiftWeight": 15.0,
          "MaxLiftSpeed": 18.0,
          "MaxTransversalSpeed": 100.0,
      },
      {
          "Make": "Spanco",
          "Model": "PF-Series 20T Gantry Crane",
          "MaxLiftWeight": 20.0,
          "MaxLiftSpeed": 15.0,
          "MaxTransversalSpeed": 80.0,
      },
      {
          "Make": "GH Cranes",
          "Model": "GHA 7.5T Double Girder",
          "MaxLiftWeight": 7.5,
          "MaxLiftSpeed": 28.0,
          "MaxTransversalSpeed": 140.0,
      },
      {
          "Make": "Yale",
          "Model": "YJL Wire Rope Hoist 3T",
          "MaxLiftWeight": 3.0,
          "MaxLiftSpeed": 35.0,
          "MaxTransversalSpeed": 180.0,
      },
      {
          "Make": "CM Lodestar",
          "Model": "Heavy Duty 1T Jib Crane",
          "MaxLiftWeight": 1.0,
          "MaxLiftSpeed": 50.0,
          "MaxTransversalSpeed": 220.0,
      },
      {
          "Make": "Deshazo",
          "Model": "Industrial Heavy Duty 25T",
          "MaxLiftWeight": 25.0,
          "MaxLiftSpeed": 12.0,
          "MaxTransversalSpeed": 75.0,
      },
      {
          "Make": "Whiting",
          "Model": "Custom Engineered 50T Heavy Crane",
          "MaxLiftWeight": 50.0,
          "MaxLiftSpeed": 10.0,
          "MaxTransversalSpeed": 60.0,
      },
  ]
